### ISSUE TITLE
AWS E2E tests

### ISSUE THREAD

**Issue by supershal** [d2iq-labs/capi-runtime-extensions#231]
Implement a E2E test that can 
- deploy a functioning cluster in AWS
- Run cluster health test
- teardown the cluster
- create a Github Actions job that runs e2e tests. Make sure that the runner is capable of creating kind cluster

**Comment by jimmidyson** [comment]
#360 introduces e2e tests for docker provider. Will discuss with @fatz how/if we can add aws tests here too, I do agree it would be useful.

**Comment by jimmidyson** [comment]
Added e2e tests in #408.
