### ISSUE TITLE
Support http proxy configuration using a topology webhook

### ISSUE THREAD

**Issue by dlipovetsky** [d2iq-labs/capi-runtime-extensions#30]
To configure the cluster control and data plane to use an HTTP proxy, users need to provide two pieces of information:
1. The http proxy URL (See the `HTTP_PROXY`, `HTTPS_PROXY` env vars)
2. A set of IPs, DNS records, and CIDRs that must be reached directly, _not_ through the proxy (See the `NO_PROXY` env var)

Providing (1) is trivial.

Providing (2) is not; values include localhost names and IPs, the cluster Pod network CIDR, Services CIDR, the cluster DNS zone, the "metadata service," and some infrastructure-dependent values. A typical value for a cluster in AWS might be:

```
localhost,127.0.0.1,10.96.0.0/12,192.168.0.0/16,kubernetes,kubernetes.default,kubernetes.default.svc,kubernetes.default.svc.cluster,kubernetes.default.svc.cluster.local,.svc,.svc.cluster,.svc.cluster.local,169.254.169.254,.elb.amazonaws.com
```

A user can discover these different values, but doing so is a lot of work. A topology webhook should be able to derive most (hopefully, all) the _required_ values for the user, and allow the user to provide optional values in addition to the required ones.

**Comment by jimmidyson** [comment]
Brilliant idea! How would a cluster opt in to this though? Label selector? Possibly using annotation? Thinking about multiple clusters in same NS, that have different proxies to use.

**Comment by jimmidyson** [comment]
@dlipovetsky Why is `.elb.amazonaws.com` required (obviously for AWS only I mean)?

**Comment by dlipovetsky** [comment]
@jimmidyson Looks like I grabbed that string from our an internal e2e test, which happens to run in AWS.

**Comment by dlipovetsky** [comment]
Done!
