### ISSUE TITLE
Refer to a single credential using the singular, instead of the plural "credentials" 

### ISSUE THREAD

**Issue by dlipovetsky** [d2iq-labs/capi-runtime-extensions#323]

**Comment by jimmidyson** [comment]
I'm not fussy about this tbh but I think generally credentials is actually more widely used, and is technically as correct as credential. https://english.stackexchange.com/questions/252073/which-is-correct-credential-or-credentials

**Comment by jimmidyson** [comment]
@dlipovetsky are you ok with closing this or do you still feel we should change this?

**Comment by dlipovetsky** [comment]
Interesting! 

It could get confusing with a slice of credentials, but our API doesn't have one now, so nothing to worry about.
